// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fy2Wd7JJUEGBqb9w6rWnVF
// Component: C7Ncz1Tinn1e

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: fy2Wd7JJUEGBqb9w6rWnVF/projectcss
import sty from "./PlasmicNoButtonQuestionContainer.module.css"; // plasmic-import: C7Ncz1Tinn1e/css

import ThumbsDownRegularSvgIcon from "./icons/PlasmicIcon__ThumbsDownRegularSvg"; // plasmic-import: cp_YUxHfLeDi/icon

createPlasmicElementProxy;

export type PlasmicNoButtonQuestionContainer__VariantMembers = {};
export type PlasmicNoButtonQuestionContainer__VariantsArgs = {};
type VariantPropType = keyof PlasmicNoButtonQuestionContainer__VariantsArgs;
export const PlasmicNoButtonQuestionContainer__VariantProps =
  new Array<VariantPropType>();

export type PlasmicNoButtonQuestionContainer__ArgsType = {
  onClickNo?: () => void;
  answerNo?: string;
};
type ArgPropType = keyof PlasmicNoButtonQuestionContainer__ArgsType;
export const PlasmicNoButtonQuestionContainer__ArgProps =
  new Array<ArgPropType>("onClickNo", "answerNo");

export type PlasmicNoButtonQuestionContainer__OverridesType = {
  root?: Flex__<"div">;
  svg?: Flex__<"svg">;
  text?: Flex__<"div">;
};

export interface DefaultNoButtonQuestionContainerProps {
  onClickNo?: () => void;
  answerNo?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNoButtonQuestionContainer__RenderFunc(props: {
  variants: PlasmicNoButtonQuestionContainer__VariantsArgs;
  args: PlasmicNoButtonQuestionContainer__ArgsType;
  overrides: PlasmicNoButtonQuestionContainer__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      onClick={async event => {
        const $steps = {};

        $steps["runOnClickNo"] = true
          ? (() => {
              const actionArgs = { eventRef: $props["onClickNo"] };
              return (({ eventRef, args }) => {
                return eventRef?.(...(args ?? []));
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["runOnClickNo"] != null &&
          typeof $steps["runOnClickNo"] === "object" &&
          typeof $steps["runOnClickNo"].then === "function"
        ) {
          $steps["runOnClickNo"] = await $steps["runOnClickNo"];
        }
      }}
    >
      <ThumbsDownRegularSvgIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg)}
        role={"img"}
      />

      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        <React.Fragment>
          {(() => {
            try {
              return $props.answerNo;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "\u062e\u06cc\u0631";
              }
              throw e;
            }
          })()}
        </React.Fragment>
      </div>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg", "text"],
  svg: ["svg"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNoButtonQuestionContainer__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNoButtonQuestionContainer__VariantsArgs;
    args?: PlasmicNoButtonQuestionContainer__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNoButtonQuestionContainer__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicNoButtonQuestionContainer__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNoButtonQuestionContainer__ArgProps,
          internalVariantPropNames:
            PlasmicNoButtonQuestionContainer__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNoButtonQuestionContainer__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNoButtonQuestionContainer";
  } else {
    func.displayName = `PlasmicNoButtonQuestionContainer.${nodeName}`;
  }
  return func;
}

export const PlasmicNoButtonQuestionContainer = Object.assign(
  // Top-level PlasmicNoButtonQuestionContainer renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicNoButtonQuestionContainer
    internalVariantProps: PlasmicNoButtonQuestionContainer__VariantProps,
    internalArgProps: PlasmicNoButtonQuestionContainer__ArgProps
  }
);

export default PlasmicNoButtonQuestionContainer;
/* prettier-ignore-end */
